index:
    path: /
    controller: App\Controller\IndexController::index

product_new:
    path: /product/new
    controller: App\Controller\ProductController::add

sales:
    path: /sales
    controller: App\Controller\SalesController::index

api:
    path: /api
    controller: App\Controller\ApiController::index

api_store:
    path: /api/store
    controller: App\Controller\ApiController::store
    methods: POST